package com.peterfonkel.webMagazine.login.roles.enums;

public enum  RolNombre {
	ROLE_ADMIN,
	ROLE_WRITER,
    ROLE_USER_MEMBER,
    ROLE_USER_MEMBER_EXPIRED,
    ROLE_USER_SUBSCRIBED,
    ROLE_USER_SUBSCRIBED_EXPIRED,
    ROLE_USER_REGISTERED,
    ROLE_USER_NOT_REGISTERED,
    ROLE_DELETED
}
